name: Setup nix
description: Setup and instal nix
inputs:
  github_token:
    description: "GitHub token for API access"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ inputs.github_token }}

    - name: Nix Install Deps
      run: nix build --accept-flake-config --no-link .#devShells.$(nix eval --impure --raw --expr 'builtins.currentSystem').default
